-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 14:23:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assignments
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `assignments` ;

-- -----------------------------------------------------
-- Schema assignments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignments` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assignments` ;

-- -----------------------------------------------------
-- Table `assignments`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignments`.`product_category` ;

CREATE TABLE IF NOT EXISTS `assignments`.`product_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `modified_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignments`.`product_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignments`.`product_inventory` ;

CREATE TABLE IF NOT EXISTS `assignments`.`product_inventory` (
  `id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `modified_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignments`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignments`.`product` ;

CREATE TABLE IF NOT EXISTS `assignments`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `SKU` VARCHAR(100) NULL DEFAULT NULL,
  `CategoryID` INT NULL DEFAULT NULL,
  `InventoryID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `CategoryID` (`CategoryID` ASC) VISIBLE,
  INDEX `InventoryID` (`InventoryID` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `assignments`.`product_category` (`id`),
  CONSTRAINT `product_ibfk_2`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `assignments`.`product_inventory` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
